web_tag_map = {
    "mutual-fund": [
        "mutual-fund",
        "mutualfund",
        "mf",
        "mutual_fund",
        "mutual fund",
        "mutual%20fund",
        "mutual+fund",
    ],
    "faq": [
        "faq",
        "frequently-asked-question",
        "frequently+asked+question",
        "frequently asked question",
    ],
    "fixed-deposit": [
        "fixed-deposit",
        "fixeddeposit",
        "fixed+deposit",
        "fixed%20deposit",
    ],
    "article": ["banking-mantra", "article", "banking mantra", "banking_mantra"],
    "credit-card": ["credit-card", "credit card", "creditcard", "credit_card"],
    "debit-card": ["debit-card", "debit card", "debitcard", "debit_card"],
    "insurance": ["insurance"],
    "loan": ["loan"],
    "bond": ["bond"],
}


mutualfund_tag_map = {
    "mutual-fund": [
        "mutual-fund",
        "mutualfund",
        "mf",
        "mutual_fund",
        "mutual fund",
        "mutual%20fund",
        "mutual+fund",
    ],
    "large-cap": [
        "large-cap",
        "largecap",
        "large_cap",
        "large cap",
        "large%20cap",
        "large+cap",
    ],
    "mid-cap": ["mid-cap", "midcap", "mid_cap", "mid cap", "mid%20cap", "mid+cap"],
    "small-cap": [
        "small-cap",
        "smallcap",
        "small_cap",
        "small cap",
        "small%20cap",
        "small+cap",
    ],
    "multi-cap": [
        "multi-cap",
        "multicap",
        "multi_cap",
        "multi cap",
        "multi%20cap",
        "multi+cap",
    ],
    "flexi-cap": [
        "flexi-cap",
        "flexicap",
        "flexi_cap",
        "flexi cap",
        "flexi%20cap",
        "flexi+cap",
    ],
    "sectoral-fund": [
        "sectoral",
        "sectoral-fund",
        "sectoral fund",
        "sectoral%20fund",
        "sectoral+fund",
    ],
    "index-fund": [
        "index-fund",
        "indexfund",
        "index_fund",
        "index fund",
        "index%20fund",
        "index+fund",
    ],
    "tax-saving-fund": [
        "tax-saving",
        "tax-saving-fund",
        "tax saving fund",
        "tax-saving%20fund",
        "tax-saving+fund",
    ],
    "liquid-fund": [
        "liquid",
        "liquid-fund",
        "liquid fund",
        "liquid%20fund",
        "liquid+fund",
    ],
    "debt-fund": ["debt", "debt-fund", "debt fund", "debt%20fund", "debt+fund"],
    "hybrid-fund": [
        "hybrid",
        "hybrid-fund",
        "hybrid fund",
        "hybrid%20fund",
        "hybrid+fund",
    ],
    "equity-fund": [
        "equity",
        "equity-fund",
        "equity fund",
        "equity%20fund",
        "equity+fund",
    ],
    "arbitrage-fund": [
        "arbitrage",
        "arbitrage-fund",
        "arbitrage fund",
        "arbitrage%20fund",
        "arbitrage+fund",
    ],
    "international-fund": [
        "international",
        "international-fund",
        "international fund",
        "international%20fund",
        "international+fund",
    ],
    "fund-of-fund": [
        "fund-of-fund",
        "fund of fund",
        "fund_of_fund",
        "fund%20of%20fund",
        "fund+of+fund",
    ],
    "retirement-fund": [
        "retirement",
        "retirement-fund",
        "retirement fund",
        "retirement%20fund",
        "retirement+fund",
    ],
}
