tickers = [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "HINDUNILVR.NS",
        "ICICIBANK.NS", "KOTAKBANK.NS", "HDFC.NS", "BAJFINANCE.NS", "ITC.NS",
        "BHARTIARTL.NS", "ASIANPAINT.NS", "LT.NS", "AXISBANK.NS", "SBIN.NS",
        "MARUTI.NS", "HCLTECH.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS", "NESTLEIND.NS",
        "TITAN.NS", "TATASTEEL.NS", "WIPRO.NS", "ADANIGREEN.NS", "DIVISLAB.NS",
        "M&M.NS", "BAJAJFINSV.NS", "POWERGRID.NS", "NTPC.NS", "GRASIM.NS",
        "TECHM.NS", "ONGC.NS", "JSWSTEEL.NS", "CIPLA.NS", "HEROMOTOCO.NS",
        "BPCL.NS", "ADANIPORTS.NS", "SHREECEM.NS", "COALINDIA.NS", "SBILIFE.NS",
        "BRITANNIA.NS", "EICHERMOT.NS", "UPL.NS", "DRREDDY.NS", "BAJAJ-AUTO.NS",
        "INDUSINDBK.NS", "IOC.NS", "HINDALCO.NS", "TATACONSUM.NS", "VEDL.NS"
    ]